### ISSUE TITLE
RuntimeError: Missing the amt.tools configuration

### ISSUE THREAD

**Issue by b-allard** [xgouchet/AutoMergeTool#16]
Hi, 

I have tried to install AMT, however when i tried it, i have the following error : 

`RuntimeError: Missing the amt.tools configuration`

Here my gitconfig : 
```
[merge]
    tool = amt
    conflictstyle = diff3

[mergetool "amt"]
    cmd = /Users/benjamin/Development/AutoMergeTool/amt.py -b "$BASE" -l "$LOCAL" -r "$REMOTE" -m "$MERGED"

[amt]
        tools = "gen_simplify;gen_woven;gen_additions;gen_deletions;meld"
        verbose = true
```

Here my tracelog : 

```
git mergetool
Merging:
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java

Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
Traceback (most recent call last):
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 215, in <module>
    result = merge(config, args, launcher, analyser)
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 177, in merge
    raise RuntimeError('Missing the {0}.{1} configuration'.format(SECT_AMT, OPT_TOOLS))
RuntimeError: Missing the amt.tools configuration

```

Could you help me ?

Thanks in advance,

Benjamin

PS : i have python 3 installed : 
```
python --version
Python 3.6.2

```

**Comment by xgouchet** [comment]
Hi Benjamin, 
I'm going to take a look into this, just a quick question, it seems that in your git config you have different padding in the different sections. Can you try updating your git config so that all options use the same number of space at  the begining of the file ? I'm not sure it's the cause, but I want to check that first

**Comment by xgouchet** [comment]
Can you open the `amt.py` file and replace the last section with this, then run the tool again ?

```python
if __name__ == '__main__':
    args = parse_arguments()

    local_config = find_local_config(args.merged)
    print(" [DBG] Local Config : " + local_config)
    config = read_config(local_config)
    print(repr(config.sections()))
    launcher = ToolsLauncher(config)
    analyser = ConflictedFileAnalyser()
    result = merge(config, args, launcher, analyser)

    if result == 0:
        clean_reports(args.merged)

    sys.exit(result)
```

**Comment by b-allard** [comment]
Hi, 

I have changed the padding and the last section, now i have the following tracelog : 

git mergetool
Merging:
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java

Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
Traceback (most recent call last):
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 212, in <module>
    print(" [DBG] Local Config : " + local_config)
TypeError: must be str, not NoneType

**Comment by xgouchet** [comment]
Ok so that narrows it down. can you remove the `print(" [DBG] Local Config : " + local_config)` line from your amt.py ? 
Sorry for the slow debug process, I need to find where this is coming from, and without being able to reproduce it :/

**Comment by b-allard** [comment]
No problem, i understand and i'm happy to help ;) 

I have remove the line, i have to try again ? In doubt : 
````
git mergetool
Merging:
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java

Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
['core', 'difftool "sourcetree"', 'mergetool "sourcetree"', 'user']
Traceback (most recent call last):
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 216, in <module>
    result = merge(config, args, launcher, analyser)
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 177, in merge
    raise RuntimeError('Missing the {0}.{1} configuration'.format(SECT_AMT, OPT_TOOLS))
RuntimeError: Missing the amt.tools configuration
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java seems unchanged.
````

**Comment by xgouchet** [comment]
Ok so apparently it's loading a git config file which might not be the one you edited. 
Can you paste the path to the gitconfig file you edited ? 

also in `amt.py`, can you add `print(GLOBAL_CONFIG)` on the line after `print(repr(config.sections()))` ?

**Comment by b-allard** [comment]
Git config in the project Android : /Users/benjamin/Development/SPMAndroid/.git/gitconfig
Location of AutoMergeTool : /Users/benjamin/Development/AutoMergeTool

```
git mergetool
Merging:
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java

Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
['core', 'difftool "sourcetree"', 'mergetool "sourcetree"', 'user']
/Users/benjamin/.gitconfig
Traceback (most recent call last):
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 217, in <module>
    result = merge(config, args, launcher, analyser)
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 177, in merge
    raise RuntimeError('Missing the {0}.{1} configuration'.format(SECT_AMT, OPT_TOOLS))
RuntimeError: Missing the amt.tools configuration
```

**Comment by xgouchet** [comment]
Ok, so it's definitely not finding the project's gitconfig (which made me realize I made an error : the  local config file should be `.git/config` and not `.git/gitconfig`... I'm fixing that later). 

Can you replace the `find_local_config` method (around line 50) by the following ? 

```python
def find_local_config(config_file):
    """
    Finds the nearest parent directory where there is a .git folder
    """
    print(" [DBG] Looking for local config in " + repr(config_file))
    parent = os.path.dirname(config_file)
    if parent == config_file:
        print(" [DBG] Found myself in a loop")
        return None

    git = os.path.join(parent, ".git")
    if os.path.exists(git):
        local_config_path = os.path.join(git, LOCAL_CONFIG_NAME)
        print(" [DBG] Found the .git folder, checking path " + repr(local_config_path))
        if os.path.exists(local_config_path):
            print(" [DBG] It exists !")
            return local_config_path
        else:
            print(" [DBG] It doesn't exist !")
            return None
    else:
        print(" [DBG] Moving up...")
        return find_local_config(parent)
```

**Comment by b-allard** [comment]
```
 git mergetool
Merging:
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java

Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm/core/activities/modules/notifications'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm/core/activities/modules'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm/core/activities'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm/core'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl/spm'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu/bgl'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java/lu'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main/java'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src/main'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app/src'
 [DBG] Moving up...
 [DBG] Looking for local config in '/Users/benjamin/Development/SPMAndroid/app'
 [DBG] Found the .git folder, checking path '/Users/benjamin/Development/SPMAndroid/.git/gitconfig'
 [DBG] It doesn't exist !
['core', 'difftool "sourcetree"', 'mergetool "sourcetree"', 'user']
/Users/benjamin/.gitconfig
Traceback (most recent call last):
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 223, in <module>
    result = merge(config, args, launcher, analyser)
  File "/Users/benjamin/Development/AutoMergeTool/amt.py", line 183, in merge
    raise RuntimeError('Missing the {0}.{1} configuration'.format(SECT_AMT, OPT_TOOLS))
RuntimeError: Missing the amt.tools configuration
app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java seems unchanged.
```

**Comment by xgouchet** [comment]
can you run `ls -l` in your `.git` folder to check the permissions ? Apparently the OS is reporting the file as "non existent"

**Comment by b-allard** [comment]
```
cd .git
ls -l
-rw-r--r--    1 benjamin  staff      41 Aug  4 10:07 COMMIT_EDITMSG
-rw-r--r--    1 benjamin  staff    1582 Aug  4 10:06 FETCH_HEAD
-rw-r--r--    1 benjamin  staff      37 Aug  4 10:11 HEAD
-rw-r--r--    1 benjamin  staff      41 Aug  4 10:11 MERGE_HEAD
-rw-r--r--    1 benjamin  staff       0 Aug  4 10:11 MERGE_MODE
-rw-r--r--    1 benjamin  staff    1548 Aug  4 10:11 MERGE_MSG
-rw-r--r--    1 benjamin  staff      41 Aug  4 10:11 ORIG_HEAD
-rw-r--r--    1 benjamin  staff     826 Aug  4 08:57 config
-rw-r--r--    1 benjamin  staff  330332 Aug  4 10:11 index
drwxr-xr-x    4 benjamin  staff     136 Jul 21 14:48 logs
drwxr-xr-x  249 benjamin  staff    8466 Aug  4 08:58 objects
-rw-r--r--    1 benjamin  staff    4806 Jul 21 14:48 packed-refs
drwxr-xr-x    6 benjamin  staff     204 Aug  4 08:58 refs
-rw-r--r--@   1 benjamin  staff     156 Aug  4 10:07 sourcetreeconfig
```

**Comment by xgouchet** [comment]
Hmm ok so indeed this is what I expected your local git config file is `.git/config`
I updated the repository, so you can download the [latest version](https://github.com/xgouchet/AutoMergeTool/archive/master.zip) and replace it on your computer, or just change the value of `LOCAL_CONFIG_NAME` line 13 : 

```python
LOCAL_CONFIG_NAME = 'config'
```

**Comment by b-allard** [comment]
Ok, it looks like it works, but apparently I doesn't have gen_simplify and meld, any idea how to resolve it ?

```
Normal merge conflict for 'app/src/main/java/lu/bgl/spm/core/activities/modules/notifications/NotificationsFragmentImpl.java':
  {local}: modified file
  {remote}: modified file
 [AMT] → Trying merge with "gen_simplify
 [AMT] — Ignoring tool "gen_simplify (unknown tool)
 [AMT] → Trying merge with gen_woven
 [AMT] ✗ gen_woven didn't solve all conflicts
 [AMT] → Trying merge with gen_additions
 [AMT] ✗ gen_additions didn't solve all conflicts
 [AMT] → Trying merge with gen_deletions
 [AMT] ? gen_deletions returned, but this should not be trusted
 [AMT] ✗ gen_deletions didn't solve all conflicts
 [AMT] → Trying merge with meld"
 [AMT] — Ignoring tool meld" (unknown tool)
 [AMT] ⚑ Sorry, it seems we can't solve it this time
```

**Comment by xgouchet** [comment]
In your config file, just remove the double quotes : 
``` tools = gen_simplify;gen_woven;gen_additions;gen_deletions;meld ```

**Comment by b-allard** [comment]
Merci infiniment ;) Now i can try the tool :)
